-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 25, 2023 at 05:23 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bazaclanaka`
--
CREATE DATABASE IF NOT EXISTS `bazaclanaka` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `bazaclanaka`;

-- --------------------------------------------------------

--
-- Table structure for table `clanci`
--

CREATE TABLE `clanci` (
  `id` int(11) NOT NULL,
  `naslov` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `sazetak` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `tekst` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `slika` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `kategorija` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `arhiva` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `clanci`
--

INSERT INTO `clanci` (`id`, `naslov`, `sazetak`, `tekst`, `slika`, `kategorija`, `arhiva`) VALUES
(88, 'NBA Finale: Rekordni preokret!', 'Neočekivana drama u finalu NBA lige s epskim preokretom.', 'U nezaboravnom finalnom susretu NBA lige, svijet košarke svjedočio je jednom od najvećih preokreta u povijesti. Utakmica je bila napeta do posljednje sekunde, a momčad koja je bila na rubu poraza uspjela je iznenaditi sve prisutne i osvojiti naslov prvaka.<br>\r\n\r\nOd samog početka utakmice, favorizirana momčad \"Vitezovi\" dominirala je terenom. Njihova kombinacija brze igre, preciznih šuteva i izvanrednih obrana ostavljala je protivničku momčad, \"Feniks\", u zaostatku. Sve je upućivalo na sigurnu pobjedu \"Vitezova\", koji su vodili s 20 poena razlike na poluvremenu.<br>\r\n\r\nNo, u drugom dijelu utakmice dogodio se nevjerojatan preokret. Momčad \"Feniks\" nije se predavala i pokazala je nevjerojatnu borbenost. Njihovi igrači su postigli seriju trica i sjajnih zakucavanja, dok su istovremeno uspjeli zaustaviti \"Vitezove\" u napadu. Rezultat je postao izjednačen, a igrači \"Feniksa\" preuzeli su inicijativu.<br>\r\n\r\nPosljednje minute bile su prepune napetosti. Obje momčadi pružale su svoj maksimum, ali \"Feniks\" je imao nadmoć. U posljednjoj sekundi, njihov igrač je postigao odlučujući koš koji je donio momčadi pobjedu s minimalnom razlikom.<br>\r\n\r\nNavijači su ostali u šoku, a igrači \"Feniksa\" proslavili su povijesnu pobjedu koja će se dugo prepričavati. Ovaj preokret podsjetio je sve zaljubljenike u košarku da je ništa nemoguće u svijetu sporta. Finale NBA lige 2023. ostat će upisano kao jedno od najuzbudljivijih i najnevjerojatnijih sportskih događaja ikad viđenih.', 'nba.jpg', 'sport', 0),
(89, 'Golijada: 10:0!', 'Nepobjedivi tim ruši rekord s deset golova u jednoj utakmici.', 'U nevjerojatnom nogometnom spektaklu koji se odigrao sinoć, momčad \"Blitz\" ostvarila je nezapamćenu pobjedu nad protivničkim timom \"Titani\" s rezultatom 10:0. Utakmica je oborila sve rekorde, a igrači \"Blitza\" pokazali su vrhunsku igru i neumoljivu napadačku moć.\r\n\r\nSusret je započeo snažnom dominacijom momčadi \"Blitz\". Već u prvom poluvremenu, njihovi napadači su postigli čak pet golova, dok su obrana i vratar održavali neprobojnu zonu. \"Titani\" su bili preplavljeni i nisu uspjeli pružiti konkurentan otpor.\r\n\r\nDrugo poluvrijeme bilo je još impresivnije za momčad \"Blitz\". Njihova kombinacija brze igre, preciznih dodavanja i vrhunskog pozicioniranja omogućila im je da redom pogađaju mrežu protivničkog tima. Njihov napadački red bio je nezaustavljiv, a \"Titani\" su se borili bezuspješno da ih zaustave.\r\n\r\nDeset golova postignutih u jednoj utakmici predstavlja povijesni trenutak za momčad \"Blitz\". Ova pobjeda potvrđuje njihovu dominaciju u ligi i postavlja nove standarde u nogometnom svijetu. Navijači su bili oduševljeni viđenim, a igrači su slavili svoj uspjeh s nevjerojatnim samopouzdanjem.\r\n\r\nUtakmica je završila s najvećom razlikom ikad zabilježenom u povijesti tog nogometnog natjecanja. Rezultat 10:0 će ostati kao nezaboravna golijada koja je ostavila pečat na nogometnu scenu. Momčad \"Blitz\" upisala je svoje ime u anale nogometa i dokazala da snaga i timski duh mogu donijeti nevjerojatne rezultate.', '2604755.jpg', 'sport', 0),
(90, 'Rekordni skokovi!', 'Sportaš obara svjetski rekord u skoku u vis.', 'U epskom trenutku sportske povijesti, mladi atletičar \"Max Jump\" postavio je novi svjetski rekord u skoku u vis. Njegov nevjerojatan skok oduševio je gledatelje i ostavio trag u atletskom svijetu.\r\n\r\nSve je počelo na sunčanom popodnevu na stadionu \"Sprint\". \"Max Jump\", talentirani atletičar koji je već privukao pažnju svojim izvanrednim skokovima, bio je fokusiran na obaranje postojećeg rekorda. Svi prisutni su bili nestrpljivi i uzbuđeni jer su osjećali da je nešto posebno u zraku.\r\n\r\nKada je \"Max Jump\" započeo svoj trk prema trampolini, atmosfera je postala električna. Svojom brzinom i snagom, izveo je savršeni skok. Njegovo tijelo je lebdjelo u zraku, a gledatelji su zadržavali dah dok je prijeđao preko visine koja se činila nepojmljivom.\r\n\r\nKada je napokon doskočio, stadion je eksplodirao u oduševljenje. \"Max Jump\" je oborio svjetski rekord, preskočivši visinu od nevjerojatnih 2.45 metara. Publika je bila u ekstazi, a sam atletičar nije mogao sakriti osmijeh na licu.\r\n\r\nOvaj rekordni skok svjedoči o iznimnom talentu i upornosti \"Max Jumpa\". Njegova predanost treningu, strast prema sportu i nepokolebljiva vjera u svoje sposobnosti donijeli su mu slavu i priznanje u atletskom svijetu.\r\n\r\n\"Max Jump\" je postao inspiracija mnogima i potaknuo nove generacije atletičara da sanjaju velike snove i teže nevjerojatnim uspjesima. Njegovo ime će ostati upisano u povijesti skoka u vis, podsjećajući nas da granice postoje samo kako bi bile premašene.', 'keyart_16_9.jpg', 'sport', 0),
(91, 'Nepobjediva ekipa!', 'Tim ostvaruje niz od 50 uzastopnih pobjeda.', 'U nevjerojatnom postignuću, sportska ekipa \"Invictus\" oborila je sve rekorde ostvarivši niz od 50 uzastopnih pobjeda. Ova nepobjediva momčad dominirala je svojim sportom i ostavila konkurenciju u potpunom šoku.\r\n\r\nOd početka sezone, \"Invictus\" je pokazao nevjerojatnu snagu, disciplinu i koheziju unutar ekipe. Svaki igrač je dao svoj maksimum na terenu, a njihova taktika i strategija bili su izvanredni. Bez obzira na protivnike, \"Invictus\" je pokazivao nepokolebljivu odlučnost i borbenost.\r\n\r\nNjihov niz pobjeda postao je glavna tema u sportskim medijima diljem svijeta. Svaka utakmica donosila je nove izazove, ali \"Invictus\" je neprestano pronalazio način da preokrene rezultat u svoju korist. Njihov stil igre bio je impresivan, a protivnici su se borili s frustracijom i očajem dok su se suočavali s tim neumoljivim timom.\r\n\r\nKroz 50 uzastopnih pobjeda, \"Invictus\" je osvajao naslove, rekordne brojeve golova i srca navijača diljem svijeta. Njihova strast prema sportu i nepopustljiva želja za uspjehom izdvojili su ih kao jedan od najdominantnijih timova u povijesti tog sporta.\r\n\r\nOva impresivna serija pobjeda svjedoči o posvećenosti, talentu i timskom duhu momčadi \"Invictus\". Oni su inspiracija za sve sportaše koji sanjaju o izvanrednim uspjesima i dokazuju da su granice samo izazov koji treba preći.\r\n\r\nSlavlje unutar momčadi i navijača \"Invictusa\" traje, a ova nepobjediva ekipa nastavit će ostavljati svoj trag u svijetu sporta. Njihov niz pobjeda nije samo dostignuće, već je postao simbol izvrsnosti i upornosti koja inspirira i potiče druge na velike uspjehe.', '4adca45a94409a319cbd4e466572df5d.png', 'sport', 0),
(92, 'Tenisač osvaja Grand Slam!', 'Outsider iznenadio svijet s osvajanjem najprestižnijeg teniskog turnira.', 'U izvanrednom preokretu događaja, nepoznati tenisač \"David Underdog\" šokirao je teniski svijet osvajanjem Grand Slam turnira. Ova senzacionalna pobjeda iznenadila je sve i stavila mladog tenisača u središte pozornosti.\r\n\r\nTurnir je započeo s velikim očekivanjima prema poznatim favoritima, ali \"David Underdog\" je postepeno privlačio pažnju svojim izvanrednim igrama. Bez obzira na njegovu anonimnost i nedostatak iskustva na najvišem nivou, tenisač je rušio protivnike jednog po jednog.\r\n\r\nU finalnom susretu, \"David Underdog\" suočio se s jednim od najboljih tenisača svijeta. Mnogi su predviđali jednostavnu pobjedu za iskusnog protivnika, ali mladi tenisač nije pokazivao strah ili pritisak. S nevjerojatnim udarcima, brzim nogama i nevjerojatnom koncentracijom, on je nadmašio sva očekivanja.\r\n\r\nUtakmica je bila prepuna nevjerojatnih poena, dugih izmjena i dramatičnih trenutaka. \"David Underdog\" je pokazao izvanrednu mentalnu i fizičku izdržljivost, pobijedivši protivnika u pet setova. Njegova hrabrost i hrabri potezi osigurali su mu titulu pobjednika Grand Slam turnira.\r\n\r\nOva senzacionalna pobjeda donijela je ne samo iznenađenje već i nadu svim mladim tenisačima koji sanjaju o velikim uspjesima. \"David Underdog\" je postao inspiracija za sve one koji se bore za svoje ciljeve i dokazao da je snaga volje i strast prema sportu moćna kombinacija.\r\n\r\nNjegovo ime će ostati zapisano u povijesti tenisa kao jedan od najnevjerojatnijih uspona i najvećih senzacija. \"David Underdog\" je dokazao da u sportu nema granica i da svaki san može postati stvarnost uz upornost, talent i vjeru u sebe.', 'SEI_110068148.jpg', 'sport', 0),
(93, 'Revolucija u košarci!', 'Inovativni tim predstavlja revolucionarnu taktiku', 'U sportskom svijetu košarke, tim \"Game Changers\" iznenadio je sve svojom revolucionarnom taktikom koja je donijela potpuno novo iskustvo igre. Njihov inovativni pristup stvorio je veliku pomutnju među protivnicima i izazvao divljenje navijača širom svijeta.\r\n\r\n\"Game Changers\" su posljednjih mjeseci tajno razvijali novu taktiku koja se temelji na preciznoj analizi protivničkih timova, strategiji i korištenju naprednih tehnologija. Konačno, oni su je odlučili primijeniti na terenu i rezultati su bili nevjerojatni.\r\n\r\nNjihova igra bila je mješavina brze tranzicije, izvanredne preciznosti dodavanja i napadačke snage. Svi igrači tima bili su uključeni u napade, izvlačeći protivnike iz ravnoteže i stvarajući prilike za nevjerojatne poene. Njihova kohezija i međusobno razumijevanje bili su izvanredni.\r\n\r\nOva nova taktika \"Game Changersa\" donijela je instantne rezultate. Tim je zabilježio seriju pobjeda nad jakim protivnicima i potvrdio svoju dominaciju na terenu. Njihova igra postala je predmet analiza i rasprava u košarkaškim krugovima, a treneri širom svijeta pokušavaju dešifrirati njihovu tajnu.\r\n\r\n\"Game Changers\" su postali inspiracija za druge košarkaške timove da razmišljaju izvan ustaljenih okvira i traže nove načine za pobjedu. Njihova hrabrost da eksperimentiraju i vjerovanje u vlastitu viziju izdvojili su ih kao predvodnike promjene u košarci.\r\n\r\nOva revolucionarna taktika obilježava novu eru u košarkaškom svijetu. Tim \"Game Changers\" postao je sinonim za inovacije i promjene, a njihov utjecaj osjetit će se u narednim godinama. Košarka više nikada neće biti ista, jer su oni otvorili vrata novim mogućnostima i neograničenim potencijalima.', 'photo-1627627256672-027a4613d028.jpeg', 'sport', 0),
(94, 'Umjetnost u plamenu!', 'Izložba vrhunskih djela završila neočekivanim incidentom.', 'Neprocjenjiva izložba vrhunskih umjetničkih djela završila je neočekivanim i tragičnim incidentom kada je požar zahvatio galeriju. Ovaj dramatičan događaj ostavio je kulturnu zajednicu u šoku i izazvao gubitak neprocjenjive vrijednosti.\r\n\r\nGalerija \"ArtEternity\" bila je domaćin iznimne izložbe koja je privukla pažnju kolekcionara, umjetničkih kritičara i ljubitelja umjetnosti diljem zemlje. Djela poznatih umjetnika bila su izložena s velikom pažnjom i sigurnošću, stvarajući atmosferu izvanredne ljepote i kreativnosti.\r\n\r\nNažalost, sudbina je odlučila drugačije. U trenutku kad su posjetitelji uživali u umjetničkom izričaju, požar je izbio iz još uvijek nepoznatih razloga. Brze vatrene stihije brzo su se proširile galerijom, gutajući bezvrijedne umjetničke artefakte.\r\n\r\nVatrogasci su brzo stigli na mjesto događaja, ali bilo je prekasno. Plameni jezik progutao je bezvremenska djela, uništavajući nezamjenjive tragove kulture. Svi su ostali bez teksta, svjesni velike tragedije koja se odvijala pred njihovim očima.\r\n\r\nOvaj događaj podsjeća nas na krhkost umjetnosti i koliko je važno čuvati i zaštititi kulturno naslijeđe. Gubitak ovih djela ne samo da će utjecati na umjetničku scenu, već će ostaviti prazninu u srcima svih koji su cijenili ljepotu i vrijednost umjetnosti.\r\n\r\nGalerija \"ArtEternity\" najavljuje obnovu i nadu u stvaranje novih umjetničkih djela koja će se uzdići iz pepela. Kroz ovu tragediju, zajednica se ujedinjuje u podršci umjetnicima i njihovom nepokolebljivom duhu stvaranja.\r\n\r\nOvaj događaj će biti zapisan u povijesti hrvatske kulture kao tužna, ali važna lekcija o važnosti očuvanja i zaštite umjetnosti. Ona također podsjeća na snagu ljudske kreativnosti i sposobnost da se obnovi i izgradi nešto novo iz pepela.', 'ddfg.jpg', 'culture', 0),
(95, 'Revitalizacija folklora!', 'Mladi plesači donose novu energiju tradicionalnim koracima.', 'Uzbudljiva revitalizacija hrvatskog folklora započela je kroz nevjerojatnu izvedbu mladih plesača. Oni su unijeli svježinu i energiju u tradicionalne plesove, privlačeći pažnju publike diljem zemlje.\r\n\r\nKroz godine, folklor je bio snažan nositelj nacionalnog identiteta i kulturnog nasljeđa Hrvatske. Međutim, s vremenom je izgubio svoju popularnost među mlađom generacijom. No, sve se promijenilo kada je nova generacija plesača zauzela pozornicu.\r\n\r\nMladi talenti su se posvetili proučavanju tradicionalnih plesova i kostima, ali su istovremeno donijeli svoju kreativnost i suvremeni pristup izvedbi. Njihova strast, virtuoznost i sinergija na pozornici oduševili su publiku.\r\n\r\nNjihove izvedbe postale su prava senzacija, privlačeći nove generacije da se zainteresiraju za folklor i pokažu ponos za hrvatsku kulturu. Festivali folklora i koncerti postali su popularna odredišta, s mladima koji se natječu za priliku da se pridruže ovom preporođenom pokretu.\r\n\r\nRevitalizacija folklora nije samo oživjela tradicionalne plesove, već je stvorila i novi interes za narodnu glazbu, nošnje i priče koje se prenose generacijama. Mladi plesači su postali ambasadori hrvatske kulture i njihov doprinos postao je neizmjerno važan za očuvanje nacionalnog identiteta.\r\n\r\nOva nova generacija plesača nastavit će širiti ljubav prema folkloru, njegujući tradiciju i istovremeno prilagođavajući je suvremenom svijetu. Njihova predanost i talent osigurat će da hrvatski folklor živi i nadalje, donoseći radost i ponos svima koji ga dožive.', 'wallpapersd.jpg', 'culture', 0),
(96, 'Slikarska senzacija!', 'Mlada umjetnica osvaja svjetsku scenu svojim remek-djelima.', 'U eksploziji kreativnosti, mlada hrvatska slikarica \"Ana Art\" postala je senzacija umjetničke scene osvajajući svijet svojim izvanrednim remek-djelima. Njezina umjetnost izazvala je divljenje i zapalila maštu publike diljem svijeta.\r\n\r\nAna, samo 25-godišnja, svojom je slikarskom virtuoznošću brzo privukla pažnju umjetničkih kritičara i kolekcionara. Njezina sposobnost prenošenja emocija kroz boje i poteze četkicom ostavlja bez daha svakoga tko promatra njezina djela.\r\n\r\nNjezine slike kombiniraju ekspresivnost, apstrakciju i duboko osobno iskustvo. Svaka slika ima svoju priču, svoj unutarnji svijet koji Ana izražava kroz slojeve boja i tekstura. Njezina umjetnost poziva promatrače da zaronite u dubine njene mašte i istraže nijanse ljudskih osjećaja.\r\n\r\nNjezina popularnost brzo je rasla, a galerije diljem svijeta žude za izložbama njezinih slika. Njezina djela suvršeno se uklapaju u najprestižnije galerijske prostore, a kolekcionari se nadmeću kako bi postali vlasnici njezinih remek-djela.\r\n\r\nAna je postala ikona mladim umjetnicima i inspiracija mnogima koji slijede njene korake. Njena strast i predanost slikanju prenose se na generacije koje dolaze, ističući snagu kreativnosti i umjetnosti u hrvatskoj kulturi.\r\n\r\nNjezina putovanja svijetom donose nove izazove i mogućnosti za rast i daljnji razvoj. Svojim talentom i jedinstvenim stilom, Ana Art ostavlja neizbrisiv trag u svjetskoj umjetnosti i donosi ponos hrvatskoj kulturnoj baštini.\r\n\r\nUpravo sada, svijet čeka s nestrpljenjem na njezinu sljedeću izložbu, spremni da budu očarani njezinom slikarskom senzacijom.', 'geo8.jpg', 'culture', 0),
(97, 'Genijalni pronalazak!', 'Hrvatski znanstvenici otkrivaju revolucionarnu tehnologiju.', 'Hrvatski znanstvenici šokirali su svijet svojim genijalnim pronalaskom - revolucionarnom tehnologijom koja bi mogla promijeniti našu percepciju svijeta. Njihovo otkriće otvara nove horizonte i donosi nadu za napredak u raznim područjima.\r\n\r\nTim znanstvenika s Instituta za napredne istraživačke tehnologije (INiT) uspio je razviti inovativnu tehnologiju koja omogućuje manipulaciju elektromagnetskim poljima na način koji dosad nije bio moguć. Njihov pronalazak ima potencijal za revoluciju u područjima poput komunikacija, energetike i medicine.\r\n\r\nOva nova tehnologija omogućuje kontrolu elektromagnetskih valova na mikroskopskoj razini, što otvara vrata za razvoj bržih i učinkovitijih komunikacijskih sustava. Također ima potencijal za generiranje čiste i obnovljive energije, pružajući održive rješenja za energetske potrebe svijeta.\r\n\r\nAli to nije sve. Znanstvenici tvrde da njihov pronalazak može imati i revolucionarni utjecaj u medicinskom području. Mogućnosti primjene ove tehnologije u dijagnostici, terapiji i istraživanju bolesti su nevjerojatne. Mnogi se nadaju da će ova tehnologija pomoći u pronalasku novih načina liječenja teških bolesti i poboljšanju zdravlja ljudi diljem svijeta.\r\n\r\nZnanstvenici su svjesni da je ovo tek početak. Njihova istraživanja i dalje su u tijeku, a njihov tim radi na daljnjem razvoju i primjeni ove tehnologije. U međuvremenu, znanstvena zajednica i industrija s nestrpljenjem prate svaki korak i nadaju se ostvarenju potencijala ovog izvanrednog otkrića.\r\n\r\nHrvatska znanstvena zajednica ponosna je na ovaj izvanredan uspjeh i nada se da će njihov pronalazak biti prekretnica u svjetskoj znanosti. Ova vijest donosi optimizam i nadu da će hrvatski znanstvenici i dalje biti vođe u istraživanju i inovacijama, ostavljajući neizbrisiv trag u svijetu znanosti.', 'electromn.jpg', 'science', 0),
(98, 'Revolucionarni lijek!', 'Hrvatski znanstvenici otkrili novi lijek za teške bolesti.', 'U senzacionalnom otkriću, hrvatski znanstvenici su razvili revolucionarni lijek koji bi mogao promijeniti način liječenja teških bolesti. Njihov pronalazak donosi nadu za milijune ljudi diljem svijeta koji se bore s ozbiljnim zdravstvenim stanjima.\r\n\r\nTim stručnjaka iz Instituta za medicinska istraživanja (IMI) uspio je pronaći inovativni pristup u borbi protiv različitih bolesti. Njihov lijek, nazvan \"CureX\", pokazao je izvanredne rezultate u prethodnim laboratorijskim ispitivanjima.\r\n\r\n\"CureX\" djeluje na molekularnoj razini, ciljajući specifične metaboličke procese u tijelu koji su povezani s bolestima poput raka, autoimunih bolesti i neurodegenerativnih poremećaja. Preliminarni rezultati istraživanja pokazuju da lijek može usporiti napredovanje bolesti i čak potaknuti regeneraciju oštećenih stanica.\r\n\r\nOva vijest je izazvala veliko uzbuđenje u medicinskoj zajednici, a znanstvenici i liječnici diljem svijeta željno iščekuju daljnje kliničke studije kako bi potvrdili učinkovitost \"CureX\"-a. Ako se pokaže uspješnim, ovaj lijek bi mogao pružiti nadu za mnoge pacijente koji se suočavaju s teškim bolestima za koje trenutno ne postoji adekvatno liječenje.\r\n\r\nHrvatski znanstvenici su puni nade i optimizma te smatraju da bi \"CureX\" mogao postati revolucionarni korak u medicinskoj terapiji. Oni su predani daljnjem istraživanju i razvoju lijeka te surađuju s međunarodnim partnerima kako bi što prije doveli ovaj lijek do pacijenata.\r\n\r\nNadamo se da će ovo otkriće postati značajan iskorak u medicinskoj znanosti i omogućiti liječenje bolesti koje su do sada bile izazovne ili nemoguće za suzbijanje. Ova vijest donosi nadu i potiče vjeru u sposobnost znanosti da pobijedi i izliječi najteže bolesti, pružajući bolji život svima koji se bore s njima.', '7182.jpg', 'science', 0),
(99, 'Kvantni proboj!', 'Hrvatski znanstvenici ostvarili revolucionarni napredak u kvantnoj fizici.', 'Hrvatski znanstvenici su postigli senzacionalni kvantni proboj koji bi mogao promijeniti način na koji shvaćamo svemir i tehnologiju. Njihov izvanredan napredak u kvantnoj fizici otvara vrata za revolucionarne tehnološke inovacije.\r\n\r\nTim znanstvenika s Instituta za naprednu kvantnu fiziku (INKF) uspio je manipulirati kvantnim stanjima čestica na dosad neviđen način. Njihov eksperiment, nazvan \"Projekt Kvantum\", donosi novu razinu preciznosti i kontrolu u kvantnoj fizici.\r\n\r\nKvantna fizika se bavi proučavanjem najosnovnijih čestica i njihovog ponašanja na kvantnoj razini. Ovaj napredak u razumijevanju kvantnog svijeta otvara mogućnosti za razvoj kvantnih računalnih sustava, kvantne komunikacije i kvantne kriptografije.\r\n\r\nZnanstvenici su uspjeli manipulirati kvantnim entanglementom, fenomenom u kojem su čestice međusobno povezane na način koji ne može biti objašnjen klasičnom fizikom. Njihov napredak u kontroliranju entanglementa ima potencijal za stvaranje superbrzih i supermoćnih kvantnih računalnih sustava.\r\n\r\nOvaj kvantni proboj donosi nadu za napredak u brojnim industrijama. Od farmaceutike do financija, kvantna tehnologija ima potencijal za rješavanje složenih problema i optimizaciju procesa na načine koji su nezamislivi sadašnjom klasičnom tehnologijom.\r\n\r\nHrvatski znanstvenici su ponosni na svoje postignuće i raduju se daljnjim istraživanjima u području kvantne fizike. Njihov uspjeh potvrđuje da je Hrvatska znanstvena zajednica na svjetskoj razini i da ima potencijal za ostvarivanje vrhunskih dostignuća u znanosti.\r\n\r\nOvaj kvantni proboj donosi novu eru u tehnološkom napretku i pokreće nas prema budućnosti u kojoj će kvantna tehnologija postati svakodnevna stvarnost. Nadamo se da će daljnja istraživanja i primjene kvantne fizike omogućiti inovacije koje će oblikovati našu budućnost na nevjerojatan način.', 'tl3sxpC-asset.jpg', 'science', 0),
(100, 'Izvanredna otkrića!', 'Hrvatski znanstvenici objavljuju senzacionalne rezultate istraživanja.', 'Hrvatski znanstvenici su objavili izvanredne rezultate svog najnovijeg istraživanja koje bi moglo promijeniti naše razumijevanje svijeta oko nas. Njihova otkrića su izuzetno uzbudljiva i otvaraju put za daljnje inovacije.\r\n\r\nTim znanstvenika s Instituta za napredna istraživanja (INAI) proveo je opsežne eksperimente i analize, istražujući fundamentalne zakone prirode. Njihova istraživanja su otkrila nove perspektive i nevjerojatne pojave koje su dosad bile nepoznate.\r\n\r\nJedno od najzapanjujućih otkrića je vezano uz kvantnu fiziku. Znanstvenici su uspjeli demonstrirati kvantno teleportiranje na makroskopskoj razini, što je dosad bilo nezamislivo. Ovo otkriće ima ogroman potencijal za razvoj bržih i sigurnijih prijenosa podataka.\r\n\r\nDrugo izvanredno otkriće odnosi se na istraživanje svemira. Korištenjem najnaprednijih teleskopa, znanstvenici su otkrili novu galaksiju udaljenu milijarde svjetlosnih godina. Ta galaksija pruža nova saznanja o formiranju i evoluciji svemira.\r\n\r\nOsim toga, znanstvenici su uspjeli razviti novi materijal s izvanrednim električnim svojstvima. Ovaj materijal bi mogao imati primjene u elektronici, energiji i medicini, otvarajući vrata za napredak u tim područjima.\r\n\r\nOva istraživanja pokazuju da je Hrvatska znanstvena zajednica na samom vrhu svjetske znanosti. Njihova predanost, stručnost i inovativnost čine ih vodećim akterima u istraživanju i otkrivanju novih saznanja.\r\n\r\nNadamo se da će ova izvanredna otkrića potaknuti daljnje istraživačke projekte i suradnju među znanstvenicima diljem svijeta. Hrvatski znanstvenici su ponosni na svoj doprinos i nastavit će raditi na otkrivanju novih tajni prirode kako bi unaprijedili naše znanje i koristili ga za dobrobit čovječanstva.', 'doctor-strang.jpg', 'science', 0),
(101, 'Veliki uspjeh!', 'Hrvatski sportaš obara svjetski rekord.', 'Hrvatski sportaš je postigao veliki uspjeh i oborio svjetski rekord u svojoj disciplini. Njegova izvanredna izvedba je oduševila svijet sporta i postala povijesna.\r\n\r\nUz nevjerojatnu snagu, brzinu i tehniku, hrvatski sportaš je nadmašio sve dosadašnje rezultate u svojoj disciplini. Njegov uspjeh je rezultat dugogodišnjeg napornog treninga, predanosti i strasti prema sportu.\r\n\r\nOvaj sportski podvig donosi ponos i slavu Hrvatskoj, a sportaš je postao istinski nacionalni heroj. Njegova izvanredna izvedba je inspiracija za mlade sportaše diljem zemlje i pokazuje da je s trudom i upornošću moguće ostvariti nevjerojatne rezultate.\r\n\r\nSvjetski mediji su preplavljeni pohvalama i priznanjima za hrvatskog sportaša. Njegova izvedba je opisana kao bezvremenska i nevjerojatna, obarajući sve prethodne granice i postavljajući nove standarde u toj disciplini.\r\n\r\nOvaj uspjeh je samo početak za hrvatskog sportaša, koji već ima ambicije i ciljeve za budućnost. Njegova posvećenost i želja za napretkom su neizmjerni, a svijet s nestrpljenjem iščekuje njegove daljnje nastupe.\r\n\r\nNjegova izvanredna izvedba će ostati zauvijek zapisana u sportskoj povijesti, a on će biti upamćen kao jedan od najvećih sportaša svih vremena. Hrvatska se ponosi njegovim postignućima i slavi njegovu nevjerojatnu vještinu i talent.\r\n\r\nOvaj uspjeh nas podsjeća da je sport izvor nadahnuća, hrabrosti i nevjerojatnih priča. On pokazuje snagu ljudskog duha i što je moguće postići kada se sanja veliko i radi naporno.\r\n\r\nČestitamo hrvatskom sportašu na izvanrednom uspjehu i želimo mu još mnogo velikih trenutaka u njegovoj karijeri.', 'images.jpeg', 'sport', 0),
(102, 'Senzacionalna pobjeda!', 'Neočekivani trijumf na svjetskom prvenstvu.', 'U nevjerojatnom obratu događaja, ekipa hrvatskih sportaša postigla je senzacionalnu pobjedu na svjetskom prvenstvu. Njihov trijumf je iznenadio sve sportske stručnjake i navijače diljem svijeta.\r\n\r\nU napetom finalnom susretu, hrvatski tim suočio se s jednim od najjačih favorita turnira. No, unatoč protivničkoj dominaciji u prvim dijelovima utakmice, hrvatski sportaši su pokazali izvanrednu hrabrost i izdržljivost.\r\n\r\nU posljednjim trenucima utakmice, kada su mnogi već izgubili nadu, hrvatski tim je uspio izjednačiti rezultat. Taj trenutak je potaknuo nevjerojatnu energiju i motivaciju kod hrvatskih sportaša koji su odlučili sve dati na terenu.\r\n\r\nU produžetku utakmice, hrvatski tim je igrao s nevjerojatnom snagom i briljantnom taktikom. Njihov izvanredan timski duh i neumorni rad doveli su ih do konačne pobjede. U posljednjim sekundama utakmice, hrvatski sportaši su postigli odlučujući gol i osigurali naslov svjetskih prvaka.\r\n\r\nOva senzacionalna pobjeda izazvala je erupciju radosti u cijeloj zemlji. Navijači su se okupili na ulicama, slaveći nevjerojatan uspjeh svojih sportaša. Hrvatski tim je postao inspiracija za sve mlade sportaše diljem zemlje koji sanjaju o velikim uspjesima na sportskom terenu.\r\n\r\nOva pobjeda će ostati upisana u povijesti hrvatskog sporta kao jedan od najvećih trenutaka. Hrvatski sportaši su dokazali da s vjerom, strašću i upornošću mogu pobijediti i nadmašiti sve prepreke.\r\n\r\nNadamo se da će ovaj izniman uspjeh potaknuti daljnji razvoj sportske kulture u Hrvatskoj i motivirati mlade talente da se ostvare u svojim sportskim karijerama. Čestitke hrvatskom timu na nevjerojatnom trijumfu i ponosu koji su donijeli svojoj zemlji!', 'images.jpeg', 'sport', 0),
(103, 'Senzacionalni rekord!', 'Hrvatski sportaš postigao nevjerojatan uspjeh.', 'U nevjerojatnom sportskom podvigu, hrvatski sportaš je oborio senzacionalni rekord koji će se dugo pamtiti. Njegovo izvanredno postignuće je izazvalo oduševljenje i divljenje širom svijeta.\r\n\r\nSportaš je ostvario nevjerojatan uspjeh u svojoj disciplini, nadmašivši sve očekivanja. Njegov talent, predanost i izuzetna fizička priprema doveli su ga do samog vrha sportske elite.\r\n\r\nU ključnom trenutku natjecanja, sportaš je pokazao nevjerojatnu snagu, izdržljivost i tehniku. Njegov podvig je bio toliko izvanredan da su mnogi gledatelji ostali bez daha dok su svjedočili povijesnom trenutku.\r\n\r\nOvaj rekord ne samo da je postavljen, već je i nadmašio prethodni najbolji rezultat za nevjerojatnih nekoliko sekundi. Sportaš je demonstrirao iznimnu kvalitetu i vještinu u svojoj disciplini, dok je publika bila zapanjena njegovom izvedbom.\r\n\r\nOvo postignuće donosi ponos ne samo sportašu, već i cijeloj Hrvatskoj. Sportaš je postao inspiracija i uzor mladim generacijama, potičući ih da slijede svoje snove i nastoje postići izvanredne rezultate.\r\n\r\nOva vijest je odjeknula diljem svijeta, a sportaš je dobio brojne čestitke od kolega, navijača i sportskih autoriteta. Njegov rekord postaje novi standard u disciplini i ostaje trajni podsjetnik na snagu ljudskog uma i tijela.\r\n\r\nNadamo se da će ovaj uspjeh potaknuti daljnji razvoj i ulaganje u sportsku infrastrukturu te podršku mladim talentima. Hrvatska se može ponositi svojim sportskim dostignućima i nastavit će graditi na tom bogatom naslijeđu kako bi donijela još više radosti i uspjeha u budućnosti.', 'images.jpeg', 'sport', 0),
(104, 'Spektakl na terenu!', 'Neočekivani preokret obilježio vrhunsku sportsku utakmicu.', 'U jednoj od najuzbudljivijih sportskih utakmica ikada viđenih, dogodio se neočekivani preokret koji je ostavio navijače bez daha. Borba na terenu između dva rivala izazvala je pravu eksploziju emocija i nevjerojatnih poteza.\r\n\r\nU napetoj igri između momčadi \"Plamen\" i \"Fulgor\", nitko nije mogao predvidjeti što će se dogoditi. \"Plamen\" je dobio vodstvo u prvom dijelu utakmice, s nevjerojatnim potezima svog najboljeg igrača, Marka Kovača.\r\n\r\nNo, u drugom dijelu utakmice, momčad \"Fulgor\" pokazala je nevjerojatnu snagu i mentalitet. Njihov kapetan, Ivan Petrović, izveo je nevjerojatnu seriju pogodaka, postižući gol za golom. Svojom preciznošću i brzinom, Petrović je oduševio gledatelje i preokrenuo rezultat u korist svoje momčadi.\r\n\r\nAtmosfera na stadionu bila je nevjerojatna, s navijačima koji su glasno bodrili svoje omiljene momčadi. Sve se činilo kao da će \"Plamen\" osvojiti pobjedu, ali \"Fulgor\" se nije predavao. Njihova upornost i timski duh donijeli su im slavnu pobjedu.\r\n\r\nKada je završilo, stadion je eksplodirao u euforiji. \"Fulgor\" je slavio svoj povijesni trijumf, a njihovi navijači su bili u transu. Ova utakmica će zasigurno ostati zabilježena kao jedna od najuzbudljivijih trenutaka u sportskoj povijesti.\r\n\r\nIako su gubitnici, igrači \"Plamena\" ponosni su na svoju izvedbu i hrabrost. Ova utakmica je dokazala snagu i kvalitetu obje momčadi, te je podsjetila na to zašto je sport tako nevjerojatan i nepredvidiv.\r\n\r\nSve u svemu, ovaj spektakl na terenu je dokazao da sportske utakmice mogu izazvati najintenzivnije emocije kod igrača i navijača. Svaki trenutak je bio prepun adrenalina, a ovakvi događaji nas podsjećaju na snagu i ljepotu sportskog natjecanja.', 'images.jpeg', 'sport', 0),
(105, 'Senzacija na terenu!', 'Najneočekivaniji preokret u povijesti sporta.', 'U nevjerojatnom preokretu koji će se dugo pamtiti, sportski svijet svjedočio je najsenzacionalnijem trenutku u povijesti. Dogodilo se nešto što je malo tko mogao predvidjeti, a to je promijenilo tijek igre i izazvalo šok među navijačima.\r\n\r\nUtakmica je započela u uobičajenoj atmosferi i očekivanjima, no nitko nije mogao naslutiti što će se dogoditi. Nepoznata momčad, koja se do tada nije istaknula u sportskom svijetu, uspjela je nadmašiti sve favorite i ostvariti pobjedu koju nitko nije očekivao.\r\n\r\nNaizgled nedodirljiva momčad prvaka suočila se s nevjerojatnim protivnikom koji je pokazao izvanredno umijeće, taktiku i hrabrost. Svaki igrač tog tima pružio je svoj najbolji nastup ikad, izvodeći nevjerojatne poteze i ostavljajući protivnike u čudu.\r\n\r\nSve je počelo s nevjerojatnim golom u ranoj fazi utakmice, koji je postavio ton za ostatak susreta. Nepoznata momčad održavala je prednost, a publika je bila u potpunom šoku. Bilo je trenutaka kada su favoriti pokušali izjednačiti rezultat, ali nevjerojatna obrana i disciplinirana igra protivnika su ih zaustavili.\r\n\r\nNakon završnog zvižduka, navijači su bili izvan sebe od sreće i iznenađenja. Nitko nije mogao vjerovati što su upravo svjedočili. Ova senzacija na terenu će ostati zapisana u povijesti sporta kao jedan od najvećih preokreta i najnevjerojatnijih iznenađenja.\r\n\r\nOva nepoznata momčad pokazala je svijetu da se sportska magija može dogoditi u najneočekivanijim trenucima. Njihov trijumf će inspirirati mnoge druge, dok će favoriti morati prihvatiti ovaj poraz kao podsjetnik da u sportu ništa nije zagarantirano.\r\n\r\nOva nevjerojatna sportska priča pokazuje koliko je lijepo biti svjedok iznenađenja i kako sport može pokrenuti strasti i emocije. Bez obzira na rezultat, ona nas podsjeća da se uvijek trebamo nadati, sanjati i vjerovati u moć sporta.', 'images.jpeg', 'sport', 0),
(106, 'Senacionalna pobjeda!', 'Neočekivani preokret', 'U dramatičnoj sportskoj utakmici koja je održana sinoć, momčad \"Vatrenih\" ostvarila je senacionalnu pobjedu protiv dosad neprikosnovenih prvaka. Nakon neizvjesnih 90 minuta igre, domaći su igrači iznenadili sve prisutne preokretom koji će se još dugo prepričavati. Iako su protivnici stekli uvjerljivu prednost u prvom poluvremenu, hrabri \"Vatreni\" nisu se predavali. U drugom dijelu utakmice, izvrsnom taktikom i nevjerojatnom izdržljivošću, uspjeli su nadoknaditi zaostatak i izjednačiti rezultat. Trenutak istine dogodio se u završnici utakmice kada je mladi napadač postigao pobjedonosni gol iz spektakularne akcije. Slavlje je eksplodiralo na stadionu dok su navijači u transu dočekali taj povijesni trenutak. Momčad \"Vatrenih\" pokazala je da se ni u najtežim trenucima ne smije odustati te da snaga volje i zajedništvo mogu pomesti sve prepreke. Ova senzacionalna pobjeda obilježit će povijest sporta i ostati u srcima svih ljubitelja nogometa.', 'images.jpeg', 'sport', 0),
(107, 'Senzacija! Tim X pobjeđuje!', 'Nepobjedivi tim X osvaja sve turnire!', 'U sportskom svijetu rijetko kad se dogodi senzacija poput ove. Tim X, bez sumnje, postao je legenda. S njihovim zadivljujućim nizom pobjeda, nadmašili su sve konkurente i osvojili sve turnire kojima su pristupili.\r\n\r\nOd samog početka sezone, Tim X ostavljao je suparnike bez daha. Njihova taktička igra, brzina i nadljudska snaga nadmašivali su sve prethodne standarde. Nitko nije mogao predvidjeti takav uspjeh.\r\n\r\nPrva utakmica sezone bila je samo uvod u ono što će slijediti. Tim X dominirao je terenom, postižući golove iz svih kutova. Suparnički timovi bili su nemoćni, ne znajući kako se oduprijeti njihovoj izvanrednoj sinergiji.\r\n\r\nSvaki turnir donosio je istu priču. Tim X prolazio je kroz protivnike kao vrući nož kroz maslac. Njihovi igrači bili su nezaustavljivi, pokazujući nevjerojatnu tehniku i strast prema igri.\r\n\r\nČini se da je tajna njihovog uspjeha njihova nevjerojatna sinergija. Svaki igrač je znao točno što očekivati od svog suigrača, bez potrebe za verbalnom komunikacijom. To je rezultiralo brzim i preciznim potezima na terenu, koji su suparnike ostavljali bez ikakve šanse.\r\n\r\nNavijači su bili oduševljeni. Tribine su se svaki put pretvarale u vulkane bučnosti i podrške. Pljesak i navijanje za tim X bili su glasniji od bilo kojeg drugog zvuka u areni.\r\n\r\nKad je Tim X osvojio posljednji turnir, atmosfera je bila eksplozivna. Proslava je trajala do kasno u noć, a grad je bio obasjan vatrometom. Tim X postao je simbol sportskog genijaliteta i inspiracije za sve mlade sportaše diljem svijeta.\r\n\r\nNo, hoće li ovaj niz nepobjedivosti trajati? Samo vrijeme će pokazati. Ali za sada, Tim X neka uživa u svom zasluženom uspjehu i tituli najboljeg tima na svijetu.', 'images.jpeg', 'sport', 0);

-- --------------------------------------------------------

--
-- Table structure for table `korisnik`
--

CREATE TABLE `korisnik` (
  `id` int(11) NOT NULL,
  `ime` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `prezime` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `kime` varchar(64) NOT NULL,
  `lozinka` varchar(255) NOT NULL,
  `razina` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `korisnik`
--

INSERT INTO `korisnik` (`id`, `ime`, `prezime`, `kime`, `lozinka`, `razina`) VALUES
(1, 'marko', 'faletar', 'markof', '$2y$10$K6YudMNfvTBSafnDi9geSuHJCcsR0196O4Df73XVaWLoPWTORQjeW', 1),
(3, 'lovre', 'batinjan', 'lovreb', '$2y$10$1kHnSlQ5Oi8/o.TnT.S5guHA.MrD93sQRhZ.Ikjw0enhWipvCH2sK', 0),
(16, 'kiki', 'horvat', 'kikih', '$2y$10$vAjnIqspAQjxdndq6wghMepCxUljN98CErEKrnzbZLYm40747zm12', 0),
(17, 'sdf', 'sdf', 'sdf', '$2y$10$zO7IKiRnXsrUEqN6Ffomguf5vyb/AUPH1vQ0s5bPmq2b6KyxucyxO', 0),
(18, 'ooo', 'ooo', 'ooo', '$2y$10$fc2QeYrnx2KRS8PF6AKVHu.JYPJm11KMNTWDbst.ay0.4Q..QvfSC', 0),
(19, 'www', 'www', 'www', '$2y$10$IFNi3FM4SY.yGDRmqK1jGe.Qqc1EG1tYfL.nFixGY7RaJVC.nsPBW', 0),
(20, 'qqq', 'qqq', 'qqq', '$2y$10$bjMmzUWgJn/ITYGIfP3CgOQHEiGRY46D9kXsDxqs.5.p21kCe8oDa', 0),
(21, 'yyy', 'yyy', 'yyy', '$2y$10$gbeVjnHxXw8RVXUovLzVCOq5Tk2/coAUDFnqB6V.HKwj3pMh3Be.q', 0),
(22, 'ggg', 'ggg', 'ggg', '$2y$10$Giw8rk0pFwbeAQgQzPU/KOVSLwIiR/.ZfdvfLS37j3nLWHfMLgDvy', 0),
(23, 'ivan', 'ivanasdfs', 'ivany', '$2y$10$NfL6cMJGjwIjp4nWWaKHyOYT4Hq7wBerPun2f9g02Wkdb/Z5V9uLW', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `clanci`
--
ALTER TABLE `clanci`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `korisnik`
--
ALTER TABLE `korisnik`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `kime` (`kime`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `clanci`
--
ALTER TABLE `clanci`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=108;

--
-- AUTO_INCREMENT for table `korisnik`
--
ALTER TABLE `korisnik`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
